repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ./.venv/Scripts/ruff.exe check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff-format
        entry: ./.venv/Scripts/ruff.exe format
        language: system
        types_or: [python, pyi]

      - id: end-of-file-fixer
        name: fix end of files
        entry: ./.venv/Scripts/python.exe scripts/precommit_hooks.py eof-fixer
        language: system

      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: ./.venv/Scripts/python.exe scripts/precommit_hooks.py trailing-whitespace
        language: system

      - id: check-yaml
        name: check yaml
        entry: ./.venv/Scripts/python.exe scripts/precommit_hooks.py check-yaml
        language: system
        files: \.(yaml|yml)$

      - id: check-added-large-files
        name: check for added large files
        entry: ./.venv/Scripts/python.exe scripts/precommit_hooks.py check-added-large-files --maxkb=1000
        language: system

      - id: check-ast
        name: check python ast
        entry: ./.venv/Scripts/python.exe scripts/precommit_hooks.py check-ast
        language: system
        types_or: [python, pyi]

      - id: debug-statements
        name: debug statements (python)
        entry: ./.venv/Scripts/python.exe scripts/precommit_hooks.py debug-statements
        language: system
        types_or: [python, pyi]
